### ISSUE TITLE
Not compatible with Python 3.11

### ISSUE THREAD

**Issue by hannesvanhove-tomtom** [tomtom-international/llvm-diagnostics#5]
The messages class is annotated with @dataclass. The behavior of default values changed for it and is currently breaking the behavior, receiving a stacktrace. https://docs.python.org/3/library/dataclasses.html#mutable-default-values
```
Traceback (most recent call last):
  File "/Users/xxxxxx/.cache/pre-commit/repojs_qvgtb/py_env-python3.11/bin/commisery-verify-msg", line 5, in <module>
    from commisery.cli import check
  File "/Users/xxxxxx/.cache/pre-commit/repojs_qvgtb/py_env-python3.11/lib/python3.11/site-packages/commisery/cli/__init__.py", line 28, in <module>
    from commisery.checking import (
  File "/Users/xxxxxx/.cache/pre-commit/repojs_qvgtb/py_env-python3.11/lib/python3.11/site-packages/commisery/checking.py", line 25, in <module>
    from commisery.rules import validate_commit_message_rule
  File "/Users/xxxxxx/.cache/pre-commit/repojs_qvgtb/py_env-python3.11/lib/python3.11/site-packages/commisery/rules.py", line 21, in <module>
    import llvm_diagnostics as logging
  File "/Users/xxxxxx/.cache/pre-commit/repojs_qvgtb/py_env-python3.11/lib/python3.11/site-packages/llvm_diagnostics/__init__.py", line 22, in <module>
    from llvm_diagnostics.messages import (
  File "/Users/xxxxxx/.cache/pre-commit/repojs_qvgtb/py_env-python3.11/lib/python3.11/site-packages/llvm_diagnostics/messages.py", line 37, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'llvm_diagnostics.messages.Range'> for field column_number is not allowed: use default_factory
```

**Comment by ReinAchten-TomTom** [comment]
Should be solved by: https://github.com/tomtom-international/llvm-diagnostics/pull/7
